### PR TITLE
Update CLI version to 3.4.4

### PR DESCRIPTION
**Pull request by prabeshshrestha**
New Version of Rainforest-CLi has been released. 
https://github.com/rainforestapp/rainforest-cli/releases/tag/v3.4.4

### CODE REVIEW

**Review by magni- — DISMISSED** [review]

**Comment by prabeshshrestha** [comment]
@magni- My editor replaced single quotes with double quotes somehow, had to force push the commit again . Seems like previous approval was ignored.

**Review by magni- — DISMISSED** [review]

**Comment by prabeshshrestha** [comment]
@magni- Seems like this repo requires signed off commits. I committed with `--signoff` I hope it works now .

**Review by magni- — DISMISSED** [review]
Signed off, or [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification) ?

Edit: looks like the quotes got auto-updated again 🙈

**Comment by prabeshshrestha** [comment]
The editor added single quotes again :(

**Review by magni- — DISMISSED** [review]

**Comment by prabeshshrestha** [comment]
hmm seems like it's still not signed :( .. Let me check how to do it .

**Review by magni- — APPROVED** [review]
🚢

**Comment by prabeshshrestha** [comment]
Seems like it's finally signed :)

**Pull request merged**
